import type { CICDPipeline } from "./types.js";

/**
 * Format CI/CD pipeline data into markdown for the custom section output.
 */
export function formatCICD(pipelines: CICDPipeline[]): string {
  const lines: string[] = [];
  lines.push("# CI/CD Pipelines", "");

  const bySystem = new Map<string, CICDPipeline[]>();
  for (const p of pipelines) {
    if (!bySystem.has(p.system)) bySystem.set(p.system, []);
    bySystem.get(p.system)!.push(p);
  }

  for (const [system, items] of bySystem) {
    const label = systemLabel(system);
    lines.push(`## ${label} (${items.length} workflow${items.length > 1 ? "s" : ""})`, "");

    const reusable = items.filter(p => p.isReusable);
    const regular = items.filter(p => !p.isReusable);

    // Summary table for non-reusable workflows
    if (regular.length > 0) {
      lines.push("| Workflow | Triggers | Jobs | Deploy | Environments |");
      lines.push("|---|---|---|---|---|");
      for (const p of regular) {
        const triggers = p.triggers.map(t => t.event).join(", ") || "\u2014";
        const jobCount = String(p.jobs.length);
        const deploys = uniqueNonEmpty(p.jobs.map(j => j.deployTarget)).join(", ") || "\u2014";
        const envs = p.environments?.join(", ") || "\u2014";
        lines.push(`| ${p.name} | ${triggers} | ${jobCount} | ${deploys} | ${envs} |`);
      }
      lines.push("");
    }

    // Job detail for multi-job pipelines
    for (const p of regular.filter(p => p.jobs.length > 1)) {
      lines.push(`### ${p.name}`, "");
      lines.push(`> \`${p.file}\``, "");

      if (p.concurrencyGroup) {
        lines.push(`> Concurrency: \`${p.concurrencyGroup}\``, "");
      }

      for (const j of p.jobs) {
        const needs = j.needs?.length ? ` (needs: ${j.needs.join(", ")})` : "";
        const runner = j.runner ? ` on \`${j.runner}\`` : "";
        const steps = j.stepCount > 0 ? `${j.stepCount} steps` : "approval gate";
        const deploy = j.deployTarget ? ` \u2192 **${j.deployTarget}**` : "";
        lines.push(`- **${j.name}**${runner} \u2014 ${steps}${needs}${deploy}`);
        if (j.actions?.length) {
          for (const a of j.actions.slice(0, 8)) { // Cap at 8 to avoid noise
            lines.push(`  - \`${a}\``);
          }
          if (j.actions.length > 8) {
            lines.push(`  - _...and ${j.actions.length - 8} more_`);
          }
        }
      }
      lines.push("");
    }

    // Reusable workflows
    if (reusable.length > 0) {
      lines.push("### Reusable Workflows", "");
      for (const p of reusable) {
        const jobNames = p.jobs.map(j => j.name).join(", ");
        lines.push(`- \`${p.file}\` \u2014 ${p.name} (${jobNames})`);
      }
      lines.push("");
    }

    // Secrets summary
    const allSecrets = [...new Set(items.flatMap(p => p.secrets || []))].sort();
    if (allSecrets.length > 0) {
      lines.push("### Secrets", "");
      for (const s of allSecrets) {
        lines.push(`- \`${s}\``);
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  const files = [...new Set(pipelines.map(p => p.file))].sort();
  lines.push(`_Source: ${files.join(", ")}_`);
  lines.push("_Generated by codesight-cicd-plugin_");
  lines.push("");

  return lines.join("\n");
}

function systemLabel(system: string): string {
  switch (system) {
    case "github-actions": return "GitHub Actions";
    case "circleci": return "CircleCI";
    default: return system;
  }
}

function uniqueNonEmpty(arr: (string | undefined)[]): string[] {
  return [...new Set(arr.filter(Boolean) as string[])];
}
